[versions]
agp = "8.9.3"
google-services = "4.4.1"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
firebase-messaging = "25.0.1"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-services = { id = "com.google.gms.google-services", version = "4.4.2" }